### ISSUE TITLE
Can't update CURL to ver. 7.75

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/curl-os2#1]
Using ANPM ver 1.0.6, I tried to update curl to the latest package and got this message:

ERROR with transaction check vs depsolve:curl7.dll is needed by (installed) liboauth-1.0.0-1.oc00.pentium4curl7.dll is needed by (installed) clamav-0.99.2-2.oc00.pentium4curl7.dll is needed by (installed) python-pycurl-7.19.5.1-2.oc00.pentium4curl7.dll is needed by (installed) poppler-legacy-72-0.61.1-1.oc00.L.pentium4curl7.dll is needed by (installed) poppler-0.90.1-1.oc00.pentium4curl7.dll is needed by (installed) poppler-legacy-94-0.84.0-1.oc00.L.pentium4Please report this error at http://trac.netlabs.org/rpm/

 It appears the new package tries to install curl4.dll, (and I presume delete the previous curl7.dll), but the packages listed in the error need curl7.dll. Also tried 'yum update curl' on the command line, but still get the error.

**Comment by SilvanScherrer** [comment]
Thx for trying to install. I didnt face those issues because im not using this rpm.
We will add a Curl legacy to fix it.

**Comment by SilvanScherrer** [comment]
should be fixed. If not please reopen the issue.

**Comment by DavidMcKenna** [comment]
Just noticed that Curl was updated in the 'release' repository (using ANPM 1.06) so decided to update my server (which only downloads release versions) and I get this error:

ERROR with transaction check vs depsolve:libpsl >= 0.21.1 is needed by libcurl-7.75.0-2.oc00.pentium4Please report this error at http://trac.netlabs.org/rpm/

 Looks like libpsl needs to be updated on the release channel as well... and might want to update the report location too...

**Comment by SilvanScherrer** [comment]
libpsl is moved to rel. so it should update now. thx for reporting.
yes the netlabs link should be changed. but for that we need to rebuild rpm/yum first.
